name: main

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: yarn
            - run: yarn prettier --check .
            - run: yarn build
              env:
                  CI: true

            # This definitely feels wrong, because we don't know for sure
            # if our deploy has finished building. In fact, I know it hasn't,
            # because I haven't set up git integration on this repo so that I
            # can deploy it manually.
            - name: Audit URLs using Lighthouse
              uses: treosh/lighthouse-ci-action@v2
              with:
                  urls: |
                      https://example.com/
                      https://example.com/blog
                  # budgetPath: ./budget.json # test performance budgets
                  uploadArtifacts: true # save results as an action artifacts
                  temporaryPublicStorage: true # upload lighthouse report to the temporary storage
